### ISSUE TITLE
librebooking keeps restarting

### ISSUE THREAD

**Issue by alaouiz** [LibreBooking/docker#50]
Librebooking was running ok for few weeks and then suddenly started failing continuously. The last logs from the librebooking container are as follows:

+ test -d /var/www/html/config
+ test -d /var/log/librebooking
+ test -f /var/www/html/composer-setup.php
+ pushd /var/www/html
+ php -r 'copy('\''https://getcomposer.org/installer'\'', '\''composer-setup.php'\'');'
+ php -r 'if (hash_file('\''sha384'\'', '\''composer-setup.php'\'') === '\''55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae'\'') { echo '\''Installer verified'\''; } else { echo '\''Installer corrupt'\''; unlink('\''composer-setup.php'\''); } echo PHP_EOL;'
Installer corrupt
+ php composer-setup.php
Could not open input file: composer-setup.php
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by alaouiz** [comment]
Attached the Libre booking logs.
[Librebooking_logs.txt](https://github.com/LibreBooking/docker/files/12044372/Librebooking_logs.txt)

**Comment by alaouiz** [comment]
Attached the docker compose file
[docker_compose.yml.txt](https://github.com/LibreBooking/docker/files/12044392/docker_compose.yml.txt)

**Comment by colisee** [comment]
Hi @alaouiz ,

Your issue seems to originate from the following instruction, inside the container entry point `/usr/local/bin/entrypoint.sh` 

```
php -r 'if (hash_file('\''sha384'\'', '\''composer-setup.php'\'') === '\''55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae'\'') { echo '\''Installer verified'\''; } else { echo '\''Installer corrupt'\''; unlink('\''composer-setup.php'\''); } echo PHP_EOL;'
```
The file `composer-setup.php` no longer has the expected sha384 value.

Since you are using an old image version, I would suggest you use one of the latest production image versions:
- librebooking:librebooking:2.8.5.5 (for librebooking version 2.8.5.5)
- librebooking:librebooking:2.8.6 (for librebooking version 2.8.6)

If you wish to enforce stricter version update control, then you could suffix the above with the repository version, as follows:
- librebooking:librebooking:2.8.5.5-2.1.0
- librebooking:librebooking:2.8.6-2.1.0

Please, let me know if that solved your issue.
