### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by alaouiz** [LibreBooking/docker#58]
Hello All,

I'm trying to use LDAP with the Librebooking docker and I tried to enable LDAP. 
I'm getting the following error:

![image](https://github.com/LibreBooking/docker/assets/28836700/534c75e3-f01d-49e2-a930-2d7b9e428627)

Where should I configure the LDPA settings ?
![image](https://github.com/LibreBooking/docker/assets/28836700/7a52bc4a-e31d-453a-ad5a-5911db901eae)

Regards,

Zaidan

**Comment by VitorTakami** [comment]
Good night, how did you get that ?
Because it need to mount /var/www/html

**Comment by colisee** [comment]
Hi @alaouiz 

None of the `librebooking/librebooking` images implement ldap at the moment.
I need to make some investigations and I will revert to you.

**Comment by colisee** [comment]
Hi @VitorTakami 

> Good night, how did you get that ? Because it need to mount /var/www/html

No, you do not mount `/var/www/html` with the **version-2** of the `librebooking/librebooking` images. Please refer to [the documentation](https://github.com/LibreBooking/docker/blob/develop/RUN.md)

**Comment by colisee** [comment]
Hi again @alaouiz ,

Before I make any changes to the Dockerfile, could you please run the following commands? I assume your nextcloud container is named **nextcloud**:
```
docker exec -t nextcloud bash -c 'apt update && apt upgrade -y'
docker exec -t nextcloud bash -c 'apt install -y libldap-dev'
docker exec -t nextcloud bash -c 'docker-php-ext-install ldap'
```

Then:
1. Go back to the Application configuration menu in librebooking
2. Select the configuration file `Authentication-Ldap` (by default, it is config.php)
3. Enter the LDAP configuration and update 

If it works for you, then I will make the change in the Dockerfile and generate a new image in the docker hub repository.

**Comment by alaouiz** [comment]
Thanks a lot Colisee,

After following the instructions above:

`docker exec -t librebooking bash -c 'apt update && apt upgrade -y'
docker exec -t librebooking bash -c 'curl -sSLf -o /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions'
docker exec -t librebooking bash -c 'chmod +x /usr/local/bin/install-php-extensions'
docker exec -t librebooking bash -c 'install-php-extensions ldap'
docker stop librebooking
docker start librebooking`

I'm now getting the following error:
![image](https://github.com/LibreBooking/docker/assets/28836700/c1e73a75-bb5a-4f8c-96ad-2a641d5e50db)

when I try to install url:
![image](https://github.com/LibreBooking/docker/assets/28836700/7993482a-f1e4-40fe-978d-ac4900fea91a)

Please advise. Thanks

**Comment by colisee** [comment]
Hi @alaouiz ,

Unfortunately, I found out that php-8 which is required by librebooking version 2.8.6, broke its LDAP plugin. At this stage, there is nothing I can do **now**, for the problem must be fixed in the [upstream repository](https://github.com/librebooking/app).

If this is the first time your are deploying librebooking (ie. you have no data, yet), then I can try to add the ldap extension to the old docker image `librebooking/librebooking:2.8.5.5-1.2.3` which uses php-7. Please, let me know if you are interested in.

**Comment by colisee** [comment]
Hi @alaouiz ,

I finally made the changes to `version-2` of the docker image.
Please:
1. Use the latest docker image `librebooking:librebooking:2.8.5.5-2.3.0`
2. Make sure you are mapping the correct folder `/config` in the docker image, as indicated in [the instructions](https://github.com/LibreBooking/docker/blob/develop/RUN.md)
3. Start from scratch (ie. with an empty /config)

**Comment by colisee** [comment]
@alaouiz , @VitorTakami , @effgarces

Please note that the docker images `librebooking:librebooking:2.8.6` and `librebooking:librebooking:develop` cannot use the LDAP authentication (even though the LDAP extension is now included in the image) since php-8 broke the LDAP plugin and is not fixed in in upstream.

**Comment by colisee** [comment]
Hi @alaouiz, @VitorTakami, @effgarces 

please note that the ldap plugin was just fixed in upstream. Thus, the docker image librebooking/librebooking:develop is now available and should work just fine.

As indicated before, docker image librebooking/librebooking:2.8.6 will not work with ldap and I will need to wait for the next upstream release (I guess 2.8.6.1).
